language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
env:
  - DB=sqlite
branches:
  only:
    - develop
    - tests
script:
- nosetests --with-coverage
after_success: coveralls
cache: pip
notifications:
  email: cynthia.abura@andela.com
